

<h1><?php echo $categories_names[$category_id-1];?></h1>
<h2><?=$article->gettitle();?></h2>



<?php if(file_exists(WEBROOT . 'img' .DS  .$category_id .  DS .$article->getImg() . '.jpg' )){ ?>

    <img src="/img/<?=$category_id;?>/<?=$article->getImg();?>.jpg" alt="">
<?php } elseif(file_exists(WEBROOT . 'img' .DS  .$category_id .  DS .$article->getImg(). '.jpeg' )){ ?>
    <img src="/img/<?=$category_id;?>/<?=$article->getImg();?>.jpeg" alt="">
<?php } else{?>
    <img src="/img/<?=$category_id;?>/default.jpg" alt="">
    <img src="/img/<?=$category_id;?>/default.jpeg" alt="">

<?php } ?>


<?=$article->gettext();?>
<h2>Analytic for this article</h2>

<?php if (\Library\Session::has('user')) {
       if($article->getAnalytics() ) {
            echo $article->getAnalytics();
            echo '<br><br><br>';
        }else{

           echo '<h3> There is no analytic for this article </h3>';
       }
    }else{
    $analytic= $article->getAnalytics();
        if($analytic){
        $analytic=explode('.',$analytic);
        for ($i=0; $i<=4; $i++){
            echo $analytic[$i]. '. ';
        }
        echo '<h3> Please login to read more </h3>';
        }else{

            echo '<h3> There is no analytic for this article </h3>';
        }
    }
?>






<?php $tags=explode(' ',$article->getTags()) ;?>
<?php foreach ($tags as $tag){?>
   <a href="/politics/tags/?tag=<?=$tag?>"><p class="btn btn-primary"><?=$tag;?></p></a>


<?php };?>
<br>
<br>
<br>

<p class="btn btn-primary">  <?= $article->getArticleReadNow();?> people are reading this article right now</p>
<p class="btn btn-primary">  This article was read <?= $article->getArticle_views_count()?>  times.</p>

<h1>Comment</h1>

<div id='message'></div>
<?=$Session_flash?>
<form method='post' id='feedback-form'>
    <input class="form-control" type="text" placeholder="name" name="author" value="<?=$form->author ?>"/><br>
    <textarea class="form-control" placeholder="Your comment" name="message"><?=$form->message ?></textarea><br>
    <button class="btn btn-primary">Go</button>

</form>

<?php foreach ($messages as $message):?>

<p>Comment added by  <?=$message->getUserName();?> </p>
<p><?=$message->getMessage();?></p>
    <br>


<?php endforeach;?>



