<table class="table table-striped books-list-table" style="margin: 50px auto; padding: 10px;"
       xmlns="http://www.w3.org/1999/html">
    <tr>
        <td>
            <div class="row">
                <h1>Add new article:</h1>
                <form method='post'>
                    Article title
                    <input type="text" name="article_title" value=""  class="form-control"/>
                    <br>
                    Article Text
                    <textarea name="article_text" value="" class="form-control" ></textarea>
                    <br>
                    Category
                    <select class="form-control" name="article_category_id" value="">
                        <?php foreach ($categories_names_ids as $categories_names_id):?>
                            <option><?=$categories_names_id->getCategoryId();?> <?=$categories_names_id->getCategoryName();?></option>
                        <?php endforeach;?>
                    </select>
                    <br>
                    tags (please use space between tags)
                    <input type="text" name="article_tags" value="" class="form-control"/>
                    <br>
                    Img
                    <select class="form-control" name="img" value="">
                        <?php for($i=1;$i<=25;$i++):?>
                            <option><?=$i?></option>
                        <?php endfor;?>
                    </select>
                    <br>
                    Article analytic text
                    <textarea name="article_analytics" value="" class="form-control" ></textarea>
                    <button type="submit">Add article</button>

                </form>
            </div>
        </td>
    </tr>
    </tbody>
</table>
